version: '3.8'

services:
  api:
    build: 
      context: ..
      dockerfile: localization/dockerfiles/api/Dockerfile      
      network: host    
    volumes:
        - $HOME/datasets/:/root/datasets/
    network_mode: "host" 
    restart: on-failure    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  xr_ros:
    image: "xr_ros-api"
    network_mode: "host" 
    restart: on-failure    
    depends_on:
      - api
    volumes:
        - $HOME/datasets/:/root/datasets/