version: '3.8'

services:
  api:
    build: 
      context: ..
      dockerfile: localization/dockerfiles/api/Dockerfile      
      network: host    
    volumes:
        - $HOME/datasets/:/root/datasets/
    ports:
      - 0.0.0.0:5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
